version: '3.9'

# Enter the default email address which is 'changeme@email.com' and the default password is 'MyPassword'

services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    environment:
      - TZ=Asia/Kuching
      - db_type=sqlite
    volumes:
      - /data/mealie/data:/app/data
    ports:
      - 9925:80
    restart: unless-stopped